### ISSUE TITLE
Highlighted Image Size

### ISSUE THREAD

**Issue by seyhunak** [Tinghui/HUIPatternLockView-Swift#5]
@Tinghui 

Hi, 

I'm using different sizes of normal and highlighted image. So, dotWidth'a constant value.
Normal, Highlighted images are so same width/height.

How can i override image size?

<img width="414" alt="screen shot 2016-09-07 at 1 54 34 pm" src="https://cloud.githubusercontent.com/assets/170820/18310848/8c3457e0-7509-11e6-9825-c630b66810cf.png">

Thanks.

**Comment by Tinghui** [comment]
Yes, it doesn't support different image sizes. 

But there is a trick you can do with your image files, then it looks like normal and highlighted dots have different sizes:
1. change the normal dot image file to same size with highlighted dot image, but image is surround by transparent pixels.
2. change `dotWidth` to same width with highlighted dot

For instruction, please see the attached:
![untitled](https://cloud.githubusercontent.com/assets/2646967/18334153/ca75d030-75a7-11e6-84cb-00e0c59824b2.png)

**Comment by seyhunak** [comment]
@Tinghui thanks will try, cheers.
