### ISSUE TITLE
Recommend how to create / change passcodes?

### ISSUE THREAD

**Issue by daviddelmonte** [Tinghui/HUIPatternLockView-Swift#6]
Does HUIPatternLockView allow me to create and change passcodes

 It would be great if HUIPatternLockView could do this! If this is not possible, can you please recommend a method?

Thanks

**Comment by Tinghui** [comment]
@daviddelmonte What do you mean "create and change passcodes" ?

HUIPatternLockView is designed to present the pattern drawn by user and convert the pattern to a string password to you. The managements of the password (such as saving, matching) are still belong to you.

If you mean you need a function that give it a string password it can draw the pattern for you, this is not supported right now.

**Comment by daviddelmonte** [comment]
Well, maybe I'm asking the wrong question.. In HUIPatternLockView, the passcode is preset. I want to allow users to set and change that passcode. Thanks

**Comment by Tinghui** [comment]
I still don't get your point. Could you give me an example about when why and **how** you want users to set and change the passcode with HUIPatternLockView?

**Comment by daviddelmonte** [comment]
Thanks for responding.. I see something like this.
1. If there is no saved passcode, ask the user to define one. (Show the pattern lock, save the result)
2. Then ask the user to repeat it. (Again, show the pattern lock)
3. Compare the results
4. If they match, save the passcode
5. If the codes don’t match, go back to step 1.

I could make this myself,  but it would make your control much more powerful..

**Comment by Tinghui** [comment]
Yes, these are common steps when users setting a password. But there may be different ways of showing the right result (in step 4) or the wrong result (in step 5) in different apps which they may want customize by themselves. 

For keeping the repository simple and clearly, the repository doesn't implement this feature, but you can make it yourself.

**Comment by daviddelmonte** [comment]
Thanks for your thoughts!
